# -*- coding: utf-8 -*-
"""Fibonacci.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_uTIsV6r1nt1ps1Eg-vEHtYijJ0FtaaW
"""

def fibonacci(n):
    a, b = 0, 1
    for _ in range(n):
        print(a, end=" ")
        a, b = b, a + b

# Example usage
n = int(input("Enter the number of terms: "))
fibonacci(n)